### ISSUE TITLE
Follow Java code conventions for creating a field names

### ISSUE THREAD

**Issue by Ghurtchu** [hirayui1/stratifier#1]
in Repo there's a field called `full_name` and it doesn't follow the Java code conventions, ideally it should be named as `fullName`. 

Probably it was done this way because Spring parser matches JSON field to Java field and you don't need to configure it at all, there should be a way to match `full_name` to `fullName`

```java
private String fullName;
```
is expected in the end

**Comment by hirayui1** [comment]
Spring Boot's JSON parser cannot handle the change from `full_name` (which is the original variable name from github's http response), to `fullName`. This would require me to completely change the way JSON is parsed, which Spring handles very conveniently, 4 lines of unfitting naming convention doesn't seem to be worth this effort.
