### ISSUE TITLE
improve error handling in GithubController.java

### ISSUE THREAD

**Issue by Ghurtchu** [hirayui1/stratifier#2]
Check [error handling in GitHubController](https://github.com/hirayui1/stratifier/blob/main/src/main/java/org/example/controller/GitHubController.java), line 108 - the HTTP request is called twice, in try block and then later in the catch block, this must be improved.

**Comment by hirayui1** [comment]
[c257278](https://github.com/hirayui1/stratifier/commit/c257278270f06cb5b0d452c376aa54dd004bbfad) was a faulty push, [81ce75c](https://github.com/hirayui1/stratifier/commit/81ce75c9f59ff0090225f8208bfcfbb19cffb1f7) fixes it for good by removing the unnecessary try-catch block.
